// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/catalog/domain/catalog_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4369627523554535285),
    name: 'CatalogItem',
    lastPropertyId: const obx_int.IdUid(14, 8728380390683010612),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 127955469886150822),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4079525055290429787),
        name: 'catalogId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5569330837426287415),
        name: 'barcode',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 1532148252419120835),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5946168015902266775),
        name: 'barcode1',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 664195034691134809),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8678697041974557550),
        name: 'barcode2',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7928194586525603480),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5277142466087419055),
        name: 'barcode3',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 4932604223879088670),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2348551400806260457),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 8485913699936421891),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7844281102196793267),
        name: 'model',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 3165703147547576792),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6529399723290812052),
        name: 'modelName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 61520798731180101),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5892797788039576590),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5597965565775054181),
        name: 'lastUpdateDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4531736963978775079),
        name: 'imgUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8728380390683010612),
        name: 'attrsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4369627523554535285),
    lastIndexId: const obx_int.IdUid(8, 3165703147547576792),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4540404020969726288],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2101835290539610267,
      1295538421748961593,
      2681148820280449275,
      4318051796355501538,
      5217587239940126087,
      4337140269689558051,
      6790937530051066910,
      1734938009085500417,
      2743578270744146881,
      1066522559189186156,
      5417369160916133270,
      2014029228108435066,
      4973093135799185841,
      6355832286635096535,
      8629758526488630214,
      5891696281918474198,
      8230906776629014151,
      6273840302294597253,
      5037790091883113870,
      1607701590784636450,
      1883370538253063395,
      129232267074258458,
      4065309040729867541,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CatalogItem: obx_int.EntityDefinition<CatalogItem>(
      model: _entities[0],
      toOneRelations: (CatalogItem object) => [],
      toManyRelations: (CatalogItem object) => {},
      getId: (CatalogItem object) => object.id,
      setId: (CatalogItem object, int id) {
        object.id = id;
      },
      objectToFB: (CatalogItem object, fb.Builder fbb) {
        final barcodeOffset = fbb.writeString(object.barcode);
        final barcode1Offset = fbb.writeString(object.barcode1);
        final barcode2Offset = fbb.writeString(object.barcode2);
        final barcode3Offset = fbb.writeString(object.barcode3);
        final nameOffset = fbb.writeString(object.name);
        final modelOffset = fbb.writeString(object.model);
        final modelNameOffset = fbb.writeString(object.modelName);
        final descriptionOffset = fbb.writeString(object.description);
        final imgUrlOffset = fbb.writeString(object.imgUrl);
        final attrsJsonOffset = fbb.writeString(object.attrsJson);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.catalogId);
        fbb.addOffset(2, barcodeOffset);
        fbb.addOffset(3, barcode1Offset);
        fbb.addOffset(4, barcode2Offset);
        fbb.addOffset(5, barcode3Offset);
        fbb.addOffset(6, nameOffset);
        fbb.addOffset(7, modelOffset);
        fbb.addOffset(8, modelNameOffset);
        fbb.addOffset(9, descriptionOffset);
        fbb.addFloat64(10, object.price);
        fbb.addInt64(11, object.lastUpdateDate.millisecondsSinceEpoch);
        fbb.addOffset(12, imgUrlOffset);
        fbb.addOffset(13, attrsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final catalogIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final barcodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final barcode1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final barcode2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final barcode3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final modelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final modelNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final imgUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final lastUpdateDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final attrsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = CatalogItem(
          id: idParam,
          catalogId: catalogIdParam,
          barcode: barcodeParam,
          barcode1: barcode1Param,
          barcode2: barcode2Param,
          barcode3: barcode3Param,
          name: nameParam,
          model: modelParam,
          modelName: modelNameParam,
          description: descriptionParam,
          price: priceParam,
          imgUrl: imgUrlParam,
          lastUpdateDate: lastUpdateDateParam,
          attrsJson: attrsJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CatalogItem] entity fields to define ObjectBox queries.
class CatalogItem_ {
  /// See [CatalogItem.id].
  static final id = obx.QueryIntegerProperty<CatalogItem>(
    _entities[0].properties[0],
  );

  /// See [CatalogItem.catalogId].
  static final catalogId = obx.QueryIntegerProperty<CatalogItem>(
    _entities[0].properties[1],
  );

  /// See [CatalogItem.barcode].
  static final barcode = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[2],
  );

  /// See [CatalogItem.barcode1].
  static final barcode1 = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[3],
  );

  /// See [CatalogItem.barcode2].
  static final barcode2 = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[4],
  );

  /// See [CatalogItem.barcode3].
  static final barcode3 = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[5],
  );

  /// See [CatalogItem.name].
  static final name = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[6],
  );

  /// See [CatalogItem.model].
  static final model = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[7],
  );

  /// See [CatalogItem.modelName].
  static final modelName = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[8],
  );

  /// See [CatalogItem.description].
  static final description = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[9],
  );

  /// See [CatalogItem.price].
  static final price = obx.QueryDoubleProperty<CatalogItem>(
    _entities[0].properties[10],
  );

  /// See [CatalogItem.lastUpdateDate].
  static final lastUpdateDate = obx.QueryDateProperty<CatalogItem>(
    _entities[0].properties[11],
  );

  /// See [CatalogItem.imgUrl].
  static final imgUrl = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[12],
  );

  /// See [CatalogItem.attrsJson].
  static final attrsJson = obx.QueryStringProperty<CatalogItem>(
    _entities[0].properties[13],
  );
}
