// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/catalog/domain/product.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4540404020969726288),
    name: 'Product',
    lastPropertyId: const obx_int.IdUid(23, 4065309040729867541),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4318051796355501538),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5217587239940126087),
        name: 'rfidTag',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 9024342127771394645),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4337140269689558051),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6790937530051066910),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1734938009085500417),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2743578270744146881),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1066522559189186156),
        name: 'priceCents',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5417369160916133270),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2014029228108435066),
        name: 'origin',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4973093135799185841),
        name: 'stockQty',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6355832286635096535),
        name: 'sku',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 5331415458403998681),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8629758526488630214),
        name: 'subCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5891696281918474198),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8230906776629014151),
        name: 'size',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6273840302294597253),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5037790091883113870),
        name: 'colorHex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1607701590784636450),
        name: 'material',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1883370538253063395),
        name: 'careInstructions',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 129232267074258458),
        name: 'season',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 4065309040729867541),
        name: 'originalPriceCents',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4540404020969726288),
    lastIndexId: const obx_int.IdUid(2, 5331415458403998681),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2101835290539610267,
      1295538421748961593,
      2681148820280449275,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Product: obx_int.EntityDefinition<Product>(
      model: _entities[0],
      toOneRelations: (Product object) => [],
      toManyRelations: (Product object) => {},
      getId: (Product object) => object.id,
      setId: (Product object, int id) {
        object.id = id;
      },
      objectToFB: (Product object, fb.Builder fbb) {
        final rfidTagOffset = fbb.writeString(object.rfidTag);
        final nameOffset = fbb.writeString(object.name);
        final brandOffset = fbb.writeString(object.brand);
        final descriptionOffset = fbb.writeString(object.description);
        final categoryOffset = fbb.writeString(object.category);
        final imageUrlOffset = fbb.writeString(object.imageUrl);
        final originOffset = fbb.writeString(object.origin);
        final skuOffset = fbb.writeString(object.sku);
        final subCategoryOffset = fbb.writeString(object.subCategory);
        final genderOffset = fbb.writeString(object.gender);
        final sizeOffset = fbb.writeString(object.size);
        final colorOffset = fbb.writeString(object.color);
        final colorHexOffset = fbb.writeString(object.colorHex);
        final materialOffset = fbb.writeString(object.material);
        final careInstructionsOffset = fbb.writeString(object.careInstructions);
        final seasonOffset = fbb.writeString(object.season);
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, rfidTagOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, brandOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, categoryOffset);
        fbb.addFloat64(6, object.priceCents);
        fbb.addOffset(7, imageUrlOffset);
        fbb.addOffset(9, originOffset);
        fbb.addInt64(12, object.stockQty);
        fbb.addOffset(13, skuOffset);
        fbb.addOffset(14, subCategoryOffset);
        fbb.addOffset(15, genderOffset);
        fbb.addOffset(16, sizeOffset);
        fbb.addOffset(17, colorOffset);
        fbb.addOffset(18, colorHexOffset);
        fbb.addOffset(19, materialOffset);
        fbb.addOffset(20, careInstructionsOffset);
        fbb.addOffset(21, seasonOffset);
        fbb.addFloat64(22, object.originalPriceCents);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final rfidTagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final skuParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final brandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final subCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final sizeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final colorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final colorHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final materialParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final careInstructionsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final originParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final seasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 46, '');
        final priceCentsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final originalPriceCentsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final stockQtyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final object = Product(
          id: idParam,
          rfidTag: rfidTagParam,
          sku: skuParam,
          name: nameParam,
          brand: brandParam,
          description: descriptionParam,
          category: categoryParam,
          subCategory: subCategoryParam,
          gender: genderParam,
          size: sizeParam,
          color: colorParam,
          colorHex: colorHexParam,
          material: materialParam,
          careInstructions: careInstructionsParam,
          origin: originParam,
          season: seasonParam,
          priceCents: priceCentsParam,
          originalPriceCents: originalPriceCentsParam,
          imageUrl: imageUrlParam,
          stockQty: stockQtyParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id = obx.QueryIntegerProperty<Product>(
    _entities[0].properties[0],
  );

  /// See [Product.rfidTag].
  static final rfidTag = obx.QueryStringProperty<Product>(
    _entities[0].properties[1],
  );

  /// See [Product.name].
  static final name = obx.QueryStringProperty<Product>(
    _entities[0].properties[2],
  );

  /// See [Product.brand].
  static final brand = obx.QueryStringProperty<Product>(
    _entities[0].properties[3],
  );

  /// See [Product.description].
  static final description = obx.QueryStringProperty<Product>(
    _entities[0].properties[4],
  );

  /// See [Product.category].
  static final category = obx.QueryStringProperty<Product>(
    _entities[0].properties[5],
  );

  /// See [Product.priceCents].
  static final priceCents = obx.QueryDoubleProperty<Product>(
    _entities[0].properties[6],
  );

  /// See [Product.imageUrl].
  static final imageUrl = obx.QueryStringProperty<Product>(
    _entities[0].properties[7],
  );

  /// See [Product.origin].
  static final origin = obx.QueryStringProperty<Product>(
    _entities[0].properties[8],
  );

  /// See [Product.stockQty].
  static final stockQty = obx.QueryIntegerProperty<Product>(
    _entities[0].properties[9],
  );

  /// See [Product.sku].
  static final sku = obx.QueryStringProperty<Product>(
    _entities[0].properties[10],
  );

  /// See [Product.subCategory].
  static final subCategory = obx.QueryStringProperty<Product>(
    _entities[0].properties[11],
  );

  /// See [Product.gender].
  static final gender = obx.QueryStringProperty<Product>(
    _entities[0].properties[12],
  );

  /// See [Product.size].
  static final size = obx.QueryStringProperty<Product>(
    _entities[0].properties[13],
  );

  /// See [Product.color].
  static final color = obx.QueryStringProperty<Product>(
    _entities[0].properties[14],
  );

  /// See [Product.colorHex].
  static final colorHex = obx.QueryStringProperty<Product>(
    _entities[0].properties[15],
  );

  /// See [Product.material].
  static final material = obx.QueryStringProperty<Product>(
    _entities[0].properties[16],
  );

  /// See [Product.careInstructions].
  static final careInstructions = obx.QueryStringProperty<Product>(
    _entities[0].properties[17],
  );

  /// See [Product.season].
  static final season = obx.QueryStringProperty<Product>(
    _entities[0].properties[18],
  );

  /// See [Product.originalPriceCents].
  static final originalPriceCents = obx.QueryDoubleProperty<Product>(
    _entities[0].properties[19],
  );
}
